version: '3.8'

volumes:
  mysqldata:
  mysqlinit:
  app:


services: 
  php:
    build: ./backend/php
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./backend/php:/var/www/html
      - ./data:/var/www/data
      - ./data:/var/www/html/images
      # - ./.htaccess:/var/www/html/.htaccess
    environment:
      DB_HOST: mysql
      DB_USERNAME: wettbewerbuser
      DB_PASSWORD: userpass
      DB_DATABASE_NAME: stickstoff


  vueweb:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend/src
      - ./frontend/node_modules:/frontend/node_modules

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wettbewerbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: stickstoff
    volumes:
      - ./mysql/initscripts:/docker-entrypoint-initdb.d
      - ./mysql/mysqldata:/var/lib/mysql/
  # sudo rm -rf mysqldata
  adminer:
    image: adminer
    ports:
      - 8085:8080



